#! /usr/local/bin/env python3.4

"""
Django settings for teenkerOP project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime
from mongoengine import *
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3lvy*(m+9h*v5)3y$bc_lr0rx$!cxm*6fln&xn5fofnw-cybay'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = True
ALLOWED_HOSTS = []
APPEND_SLASH=False
# Application definition

INSTALLED_APPS = (
    #'django.contrib.admin', #for admin
    'django.contrib.auth', #for admin
    'django.contrib.contenttypes', #for admin
    'django.contrib.sessions', #for admin
    'django.contrib.messages', #for admin
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_swagger',
    'rest_framework_mongoengine',
    'sleepcamp',
    # 'serviceproject',
    # 'journal',
    # 'tkopuser',
    # 'jwtauth',
    # 'tags',
    # 'delicacy',
    # 'statistication',
)

#middleware definition
MIDDLEWARE_CLASSES = (
    #'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
)

#REST FRAMEWORK definition
# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.BasicAuthentication',
#         # 'jwtauth.authentication.JSONWebTokenAuthentication',
#     ),
# }

ROOT_URLCONF = 'guanlingapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guanlingapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
       # 'ENGINE': 'django_mongodb_engine',
       # 'NAME': 'teenker',
    }
}
MONGODB_USER = 'guanling'
MONGODB_PASSWD = 'guanling'
MONGODB_HOST = '127.0.0.1'
MONGODB_NAME = 'glypnosis'
# MONGODB_NAME2 = 'iteenkerOpDb'
MONGODB_DATABASE_HOST = 'mongodb://%s:%s@%s/%s' % (MONGODB_USER, MONGODB_PASSWD, MONGODB_HOST, MONGODB_NAME)
connect(MONGODB_NAME, host = MONGODB_DATABASE_HOST)
# teenkeronline = connect(MONGODB_NAME, host = MONGODB_DATABASE_HOST)
# teenkeroffline = connect(MONGODB_NAME2, host = MONGODB_DATABASE_HOST)
# register_connection('default', 'teenkeronline')
# register_connection('teenkeropdb', 'teenkeroffline')
#mongoengine.connect(db='teenker', username='iteenker',password='iteenker')

#JWT AUTH configuration
# AUTH_USER_MODEL = 'tkopuser.TeenkerOpUser'
# JWT_AUTH = {
#     'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=3600) ,
#     'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(seconds=3600),
# }

#CORS Configuration
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = (
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'OPTIONS'
    )
CORS_ALLOW_HEADERS = (
        'x-requested-with',
        'content-type',
        'accept',
        'origin',
        'authorization',
        'x-csrftoken'
    )

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
TEMPLATE_LOADERS = {
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader'
}
TEMPLATE_DIRS = {
    os.path.join(BASE_DIR,'templates'),
}
#STATICFILES_DIRS = (
#    normpath(os.path.join(BASE_DIR, 'static')),
#    normpath(os.path.join(BASE_DIR, 'upload')),
#)
STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR,STATIC_URL.strip('/'))
STATIC_ROOT =  '/usr/local/nginx/html/static'
#STATIC_URL = '/static/'
#API version
APIVERSION = r'^api/api/v1/'



__author__ = "moonmoonbird"
__copyright__ = "Copyright 2015 , The TeenkerOperations Project"
__version__ = "1.0.1"
__maintainer__ = "moonmoonbird"
__email__ = "lomoonmoonbird@gmail.com"
__status__ = "Development"
